apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    environment: prod
spec:
  capacity:
    storage: 20Gi
  hostPath:
    path: /mnt/prod/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    environment: prod
spec:
  resources:
    requests:
      storage: 20Gi


