apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: cafeapp 
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: cafeapp 
  clusterIP: None  # This makes the service a headless service

