apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  getAppParameters.php: |
    <?php
    $showServerInfo = "true";
    $timeZone = "America/New_York";
    $currency = "£";  // Change currency to Pounds
    $db_url = "10.32.0.8";  // Use MySQL service name for internal DNS resolution
    $db_name = "mom_pop_db";
    $db_user = "root";
    $db_password = "Msois@123";

