---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: my-app-prod
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./Deploy/kustomize_cafe_app/overlays/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-app-repo
  targetNamespace: prod
