apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-virtualservice
  namespace: default
spec:
  hosts:
  - "*"
  gateways:
  - cafeweb-rollout-gateway
  http:
  - name: primary
    route:
    - destination:
        host: {{ .Release.Name }}-cafeweb-stable
        port:
          number: 80
      weight: 100
    - destination:
        host: {{ .Release.Name }}-cafeweb-canary
        port:
          number: 80
      weight: 0
