apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: cafeapp 
spec:
  selector:
    matchLabels:
      app: cafeapp 
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cafeapp 
    spec:
      containers:
      - image: sreedocker123/mompopcafedb:v1 
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: MYSQL_DATABASE
          value: mom_pop_db
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
