apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cafeapp-dev
  namespace: flux-system
spec:
  releaseName: cafeapp-dev
  chart:
    spec:
      chart: ./Deploy/Helm_Chart_CafeApp
      sourceRef:
        kind: GitRepository
        name: my-app-repo
      version: "1.0.0" # Update to the desired version of your Helm chart
  interval: 10m
  valuesFrom:
    - kind: ConfigMap
      name: values-dev
      valuesKey: values.yaml
  targetNamespace: dev

