apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: my-app-config
  namespace: flux-system
spec:
  interval: 1m
  path: "./Deploy/Helm_Chart_CafeApp"
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-app-repo
  validation: client
  targetNamespace: flux-system

