---
# Update the apt cache
- name: Update apt cache
  apt:
    update_cache: yes

# Install necessary packages
- name: Install Apache and PHP packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apache2
    - php
    - php-mysql
    - libapache2-mod-php
    - wget
    - tar

# Ensure Apache is enabled and started
- name: Ensure Apache is enabled and started
  service:
    name: apache2
    state: started
    enabled: yes

# Download the tarball containing the application code
- name: Download application code tarball
  get_url:
    url: "{{ app_tarball_url }}"
    dest: "{{ app_tarball_dest }}"

# Extract the tarball to the target directory
- name: Extract application code
  unarchive:
    src: "{{ app_tarball_dest }}"
    dest: "{{ app_extract_dest }}"
    remote_src: yes

# Ensure /etc/cafe directory exists
- name: Ensure /etc/cafe directory exists
  file:
    path: /etc/cafe
    state: directory
    mode: '0755'

# Copy getAppParameters.php template to /etc/cafe
- name: Copy getAppParameters.php template to /etc/cafe
  template:
    src: "{{ get_app_parameters_src }}"
    dest: "{{ get_app_parameters_host_dest }}"
    mode: '0644'

# Ensure /var/www/html/mompopcafe directory exists
- name: Ensure /var/www/html/mompopcafe directory exists
  file:
    path: "{{ app_extract_dest }}"
    state: directory
    mode: '0755'

# Copy the application code to the target directory
- name: Copy application code to /var/www/html/mompopcafe/
  copy:
    src: "{{ item }}"
    dest: "{{ app_extract_dest }}"
    owner: www-data
    group: www-data
    mode: '0644'
  with_fileglob: "/tmp/Cafe_Dynamic_Website/mompopcafe/*"

# Update Apache configuration to point to the application directory
- name: Update Apache configuration
  template:
    src: "{{ apache_config_template }}"
    dest: /etc/apache2/sites-available/000-default.conf
  notify: Reload Apache

