apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mysql-secret.yaml
  - mysql-pv.yaml
  - mysql-pvc.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - cafeweb-deployment.yaml
  - cafeweb-service.yaml
  - configmap.yaml

commonLabels:
  app: cafeapp

