apiVersion: builtin
kind: LabelTransformer
metadata:
  name: add-labels
labels:
  app: cafeapp
fieldSpecs:
  - path: metadata/labels
    create: true
    kind: Deployment
  - path: metadata/labels
    create: true
    kind: Service
  - path: metadata/labels
    create: true
    kind: PersistentVolume
  - path: metadata/labels
    create: true
    kind: PersistentVolumeClaim
  - path: metadata/labels
    create: true
    kind: Secret
  - path: metadata/labels
    create: true
    kind: ConfigMap

