- name: Ensure Docker is installed
  apt:
    name: docker.io
    state: present

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: true

- name: Create Docker network
  docker_network:
    name: cafeapp_network
    driver: bridge

- name: Render getAppParameters.php template
  template:
    src: getAppParameters.php.j2
    dest: /etc/cafeapp/

- name: Pull cafeweb image from Docker Hub
  docker_image:
    name: "{{ cafeweb_image }}"
    pull: true

- name: Create and start cafeweb container
  docker_container:
    name: "{{ cafeweb_container_name }}"
    image: "{{ cafeweb_image }}"
    ports:
      - "80:80"
    volumes:
      - /etc/cafeapp/getAppParameters.php.j2:/var/www/html/getAppParameters.php
    env:
      TZ: "{{ time_zone }}"
    networks:
      - name: cafeapp_network

