apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: my-app-stage 
  namespace: flux-system
spec:
  interval: 10m
  path: "./Deploy/kustomize_cafe_app/overlays/stage"
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-app-repo
  validation: client
  targetNamespace: stage 

