apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: my-app-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/sreepathysois/Cafe_Dynamic_Website.git
  ref:
    branch: main
  secretRef:
    name: flux-system

