apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cafeweb-config
  labels:
    app: cafeapp
data:
  getAppParameters.php: |
    <?php
    $showServerInfo = "{{ .Values.config.showServerInfo }}";
    $timeZone = "{{ .Values.config.timeZone }}";
    $currency = "{{ .Values.config.currency }}";
    $db_url = "{{ .Release.Name }}-mysql";
    $db_name = "{{ .Values.config.db_name }}";
    $db_user = "{{ .Values.config.db_user }}";
    $db_password = "{{ .Values.config.db_password }}";
    ?>

