apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    environment: dev
spec:
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/dev/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    environment: dev
spec:
  resources:
    requests:
      storage: 10Gi

