apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cafeapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/sreepathysois/Cafe_Dynamic_Website.git'
    targetRevision: HEAD
    path: Deploy/kustomize_cafe_app/overlays/dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

