apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cafeapp-stage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/sreepathysois/Cafe_Dynamic_Website.git'
    targetRevision: HEAD
    path: Deploy/kustomize_cafe_app/overlays/stage
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

