- name: Ensure Docker is installed
  apt:
    name: docker.io
    state: present

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: true

- name: Create Docker network
  docker_network:
    name: cafeapp_network
    driver: bridge

- name: Pull mysql image from Docker Hub
  docker_image:
    name: "{{ mysql_image }}"
    pull: true

- name: Render create-db.sql from template
  template:
    src: create-db.sql.j2
    dest: /etc/cafeapp/

- name: Create and start mysql container
  docker_container:
    name: "{{ mysql_container_name }}"
    image: "{{ mysql_image }}"
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      MYSQL_DATABASE: "{{ mysql_database }}"
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
      - /etc/cafeapp/create-db.sql.j2:/docker-entrypoint-initdb.d/create-db.sql
    networks:
      - name: cafeapp_network

