# helmrelease-cafeapp-dev.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cafeapp-dev
  namespace: dev
spec:
  interval: 5m
  chart:
    spec:
      chart: ./Deploy/Helm_Chart_CafeApp
      sourceRef:
        kind: GitRepository
        name: my-app-repo
        namespace: flux-system
  values:
    replicaCount: 1
    mysql:
      image: sreedocker123/mompopcafedb:v1
      database: mom_pop_db
      user: root
    cafeweb:
      image: sreedocker123/mompopcafeapp
      tag: v1
    persistentVolume:
      size: 10Gi
    service:
      type: NodePort 
      port: 80
    # Add other values here as needed

