- hosts: all
  become: yes

  tasks:
  - name: Install Python pip
    apt:
      name: python3-pip
      state: present

  - name: Install Docker module for Python
    pip:
      name: docker
      state: present

  - name: Include cafeweb role
    include_role:
      name: cafeweb

  - name: Include mysql role
    include_role:
      name: mysql

